### ISSUE TITLE
I need to run Sophos from the command line

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#1]
So that I can better automate the virus scan process.

**Done Looks Like**
From running a script and providing the source and destination paths, Sophos virus scan runs and saves the console log file to the destination folder.

**Comment by mccalluc** [comment]
@Muraszko : could you confirm that just running `sweep your_target` does what you want? There are a lot of options we could add if it doesn't...

**Comment by Muraszko-wgbh** [comment]
Works just how I was hoping.
