### ISSUE TITLE
Try cmp instead?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/preservation-workflow#14]
@Muraszko : if the files which produce the false positive on diff are still around, could you try cmp on them? It's a command that tries to do less, so hopefully it won't trip over whatever tripped the diff. 

I don't think there is a speed difference between the two: http://unix.stackexchange.com/questions/153286/is-cmp-faster-than-diff-q

**Comment by Muraszko-wgbh** [comment]
Closing, seems cpm is normally used for file to file comparisons.  No regular -r option to run on directories.  diff seems to work fine for now.  We can always revisit if diff shows problems.
