### ISSUE TITLE
I need to copy source files to two LTO tapes at once

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#2]
So that we can save some processing steps when making a vault and offsite LTO tape.

**Testing**
- [x] Test using `tar` to copy from source to single LTO tape.
- [ ] Test using `tar` to copy from source to multiple LTO tapes.

**Done looks like**
A script that when used and a user provides source and two destinations will successfully copy source files and folders to the two destinations.

**Comment by Muraszko-wgbh** [comment]
`tar` is pretty slow.  Nearly 5 hours so far to transfer <2TB of data.  Normal `cp` or drag and drop speed would have it around 3 hours.

**Comment by foo4thought** [comment]
assumes regular files and not links; tests for basic stuff like "does it exist?" and "is it readable/writeable?" but does not ensure any target has enough room to write

```
#!/bin/bash

function usage {
    echo "$1";
    echo '### ';
    echo;
    echo "usage:  $(basename $0) '/path/to/source' '/path/to/dest1' '/path/to/dest2'";
    echo;
    echo '###';
    echo;
    echo;
    echo 'will copy file system contents from one source to two destinations using `tar` and `tee` ';
    exit;
}

utilTest=$(for u in tar tee printf echo dirname basename;
do
    if [ -z "$(which $u)" ]
    then
        echo "$u";
    fi
done)


if [ ! -z "$utilTest" ]
then
    echo "$utilTest cannot be found" >&2
    exit 1 
fi

if [ "$#" -ne 3 ]
then
    usage "three arguments are required"
fi

src="$1";
dest1="$2";
dest2="$3";


existTest=$(for a in "$@";
    do 
        if [ ! -e "$a" ];
        then
            printf %s "'$a' ";
        fi
    done)

if [ ! -z "$existTest" ]
then
     usage "$existTest cannot be found";
fi


readTest=$(if [ ! -r "$src" ];
    then
        echo "$src is not readable"
    fi
)

writeTest=$(for t in "$dest1" "$dest2";
    do
        if [ ! -w "$t" ];
        then
            printf %s "'$t' "
        fi
    done)

badArgs=$(if [ ! -z "$readTest" ];
    then
        echo "$readTest is not readable";
    fi;
    if [ ! -z "$writeTest" ];
    then
        echo "$writeTest is not writable";
    fi
)

if [ ! -z "$badArgs" ]
then
    usage "ERROR:  $badArgs";
fi


tar -cf - -C "$(dirname $src)" "$(basename $src)" | tee >(tar -xf - -C $dest1) >(tar -xf - -C $dest2) >/dev/null
```

**Comment by mccalluc** [comment]
@Muraszko : it sounds like tar is slower, so is there another reason not to just continue with cp? What is actionable here?

**Comment by Muraszko-wgbh** [comment]
@mccalluc  Wanted to use tar because Kevin had said that we may be able to split the output and write to two tapes at the time time, while cp will write to DEST1 and then DEST2 right?  But if tar takes twice as long, we may as well just use cp.

Kevin and I have to test that outside of the preservation.sh script still.  If it seems like it would be better to use than cp I'll ping you in this ticket to change the script to tar.  If not, I'll just close this ticket.

**Comment by mccalluc** [comment]
> while cp will write to DEST1 and then DEST2

Right now, both cps are subprocesses which run in parallel: If the bottleneck is writing to tape, then I don't think there are any improvements to be made on that. It's possible that there could be contention between the two processes doing disk reads, but since the same files are being accessed in the same order, I'd hope the drive head would only need to read a given sector once, and then those bytes would be kept in cache until the second process caught up... but I'm well out of my depth here.

**Comment by Muraszko-wgbh** [comment]
I'll close for now and will make a re-open to test `tar` if for some reason `cp` doesn't behave well.
