### ISSUE TITLE
Spaces in directory names

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#22]
@mccalluc 
Sweep was failing to run because the top directory on a drive had a space in it's name.
Example "Outpost BU15"

Also noticed that the metadata report for the virus scan was ignoring the space as well.  It named the .txt file "Outpost_virus_scan.txt" ignoring the BU15 because it was after the space.

I did a quick change to the script using 

```
OLDIFS=$IFS;
IFS=`echo -en '\n\b'`;

###############
# Sophos scan
###############

```

And it ran sweep but terminated the script after that so I think all the parts of the script need to allow for spaces.

**Comment by mccalluc** [comment]
I'll put quotes around everything, and add that case to the tests.

**Comment by Muraszko** [comment]
Fixed by making script Ruby.

**Comment by Muraszko-wgbh** [comment]
Sorry reopening.  Sophos seems to be accounting for the spaces but FITS is not, see Terminal message:

```
Exception: /Users/michael_muraszko/Desktop/LTO_PRESERVATION/AAPB_LTO does not exist or is not readable
```

That folder name is named `AAPB_LTO Scripts`

Also, diff seems like it's failing to compare also:

```
diff: extra operand `/Users/michael_muraszko/Desktop/LTO_PRESERVATION/DUMP2'
diff: Try `diff --help' for more information.
diff: extra operand `/Users/michael_muraszko/Desktop/LTO_PRESERVATION/DUMP1'
diff: Try `diff --help' for more information.
```

**Comment by Muraszko-wgbh** [comment]
Interesting, the processes seem to run if the space in the folder name is not the SOURCE directory but a subdirectory.
