### ISSUE TITLE
Diff problems

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#24]
@mccalluc Just ran the Ruby version of the script and the diff created extra folders for the output 
![screen shot 2016-06-06 at 9 14 26 am](https://cloud.githubusercontent.com/assets/6650285/15823256/f222da26-2bc7-11e6-90ca-6a6cadaaa17e.jpg)

and saved them as a .diff.

**Done looks like**
Diff log files is saved as .txt
All log files are saved under METADATA/diff directory

**Comment by mccalluc** [comment]
@Muraszko, a few more thoughts: 
- Because the diffs run in parallel, they should probably be separate files: it's not impossible to have two sources appending to the same file, but the result is more confusing.
- Above, is there a particular reason you request the '.txt' extension?

**Comment by Muraszko-wgbh** [comment]
@mccalluc Good point, it would be confusing to see the lines from both all mixed together.  A diff file per destination is fine.

I would like them as .txt because it's easier for users to understand.  Seeing .diff extension (even though it would behave like a text file) means less questions if I end up sharing them with other staff or people in other departments.  "What's .diff?  How do I open it?"
