### ISSUE TITLE
More obvious difference notice

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#27]
In the Copy and Diff section of preserve.rb when the diff doesn't match it's reporting

_preserve.rb:85:in `block in fork_copy_diff': diff not clean: /Users/michael_muraszko/Desktop/METADATA/diff/dest-0.diff_

I would like the wording to be `There was a file difference found. Check the log file.` then list which .diff file to look, as it's doing already.

Also it seems the script is reporting it in Terminal as it's found.  It could get lost in in the window because FITS often will spit out many lines as it's working.  I would like if there was a difference found to again report it as the last lines before preserve.rb completes or have them get sent to a error log txt file that will automatically open when they are found.

**Done looks like**
Change in difference text
Either send differences to txt file that will automatically open or report differences again at end of process.

**Comment by mccalluc** [comment]
> FITS often will spit out many lines as it's working

@Muraszko : Could we just send the FITS output to /dev/null or a log file, unless you really need it?

**Comment by Muraszko-wgbh** [comment]
@mccalluc Yes, sending it to /dev/null would be fine.
