### ISSUE TITLE
File navigator stuck loading

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#28]
It doesn't seem to load any of my file-list.txt files.  Tried three different files, all of different sizes.

![screen shot 2016-06-10 at 1 23 56 pm](https://cloud.githubusercontent.com/assets/6650285/15972867/b70e3c9c-2f0e-11e6-86a5-707ab9914c00.jpg)

**Comment by mccalluc** [comment]
@Muraszko : The first version was very sensitive to the formatting of the file, but it should be somewhat more robust now. If you still get this behavior with the latest, attach the smallest reproducer here and I'll have a look.

**Comment by Muraszko-wgbh** [comment]
Still the same with this file.
[Ci-TEST_1-file-list.txt](https://github.com/WGBH/preservation-workflow/files/311835/Ci-TEST_1-file-list.txt)

**Comment by mccalluc** [comment]
We talked, and with the latest code the file list is in the correct format, and the JS is not cranky.
