### ISSUE TITLE
Have the diff dest.txt omit hidden files

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#35]
Currently the diff dest.txt file report includes lines listing matching hidden files

```
Files /Volumes/Public_Archives/Antiques_Roadshow/Antiques_Roadshow_To_Archives/Antiques_Season_20_Audio_Mix_Sessions_and_Web/.DS_Store and /Volumes/barcode368150/Antiques_Season_20_Audio_Mix_Sessions_and_Web/.DS_Store are identical
```

This can make for confusing file count comparisons and false positive diff warnings.

**Done looks like**
The diff dest.txt files no longer contain results for these `/.` hidden files.

**Comment by mccalluc** [comment]
Besides simply excluding these lines from the diff output, you really want then not even to be considered as part of the diff, I think? Maybe this can be done with `--exclude=PAT`.
