### ISSUE TITLE
Reuse existing file renamer?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/preservation-workflow#4]
@foo4thought: Could you give me the existing file name cleaner script? Don't want to reinvent the wheel.

**Comment by foo4thought** [comment]
IDK this.  I was surprised to learn that @Muraszko renames files because we're supposed to preserve everything as much as possible.

**Comment by Muraszko-wgbh** [comment]
@mccalluc It's not a script.  It's the [NameChanger application.](https://mrrsoftware.com/namechanger/)
@foo4thought and I are going to be testing to see if using `tar` will successfully copy over files with `/` in the filename.  Currently, my copy processes fail when copying those to LTO.

We only need to preserve filenames for certain files, there is a drive grooming process that usually occurs as part of asset delivery where things can get renamed.

I'll assign @mccalluc to this issue if our `tar` transfer test fails and close the issue if it succeeds, cool?

**Comment by foo4thought** [comment]
here's how I handle it for transfers to ISIS:

mylocal:~ kevin_carter$ echo '/some/dumb#bozo filename!.jpg' | sed -e 's#.#\&#g'
\/\s\o\m\e\/\d\u\m\b#\b\o\z\o\ \f\i\l\e\n\a\m\e!.\j\p\g

**Comment by foo4thought** [comment]
LOL  which I see fails for handling the '#' because that was my sed delimiter
you get the idea - it might be necessary to construct the sed statement judiciously, e.g., use the first from a short list of potential delimiters that don't appear in the handling of the current item/batch

**Comment by Muraszko-wgbh** [comment]
@mccalluc 
For these first runs could the rename script you're using only rename `:` and `/` to `_`?

The reason I had to rename the other characters previously was because it was throwing off the md5 csv process, but since we're not going to be comparing md5 csv files it's not needed in the rename script, just the `/` and `:` characters.
Thanks.
