### ISSUE TITLE
I need to incorporate running FITS

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#5]
So that the current version of FITS can run and generate xml on the source location's files.

[FITS 0.10.1 can be found here.](http://projects.iq.harvard.edu/fits/downloads)

Currently, I'm running this script to generate the xml.

```
$ cd to FITS installed directory

$ ./fits.sh -i /Users/michael_muraszko/SOURCE_DIRECTORTY -o \
/Users/michael_muraszko/Desktop/XML_DESTINATION_DIRECTORY/ -r
```

**Done looks like**
After defining the source and destination FITS is used to generate XML files within part of this better automated digital preservation processes.

**Comment by mccalluc** [comment]
@Muraszko : I think the current version covers this? Reopen if I'm mistaken.
