### ISSUE TITLE
I need to use diff to verify LTO copies

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#6]
So that we don't need to run and compare md5 value lists every time.

**Testing**
- [x] `diff` a source's files and single LTO copy
- [ ] `diff` a source's files and dual LTO copies at the same time

**Done looks like**
A `diff` script that let's a user define source and two destinations, saves results to a log file.

**Comment by mccalluc** [comment]
@Muraszko : Right now two destinations are required... Should you also be able to run it with a single destination?

**Comment by Muraszko-wgbh** [comment]
@mccalluc Yes, that's a good idea.  We'll also need to run the `tar` or `cp` to a single destination too.

**Comment by mccalluc** [comment]
With #20, and number of destinations can be specified. Closing.
