### ISSUE TITLE
Delete FITS.xml for hidden files

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/preservation-workflow#9]
So that we're only left with FITS.xml files in the FITS folder that are of non-hidden files.

For some directories, FITS will create xml files for any /.hidden.whatever files.  Normally I check the finished FITS directory will all the FITS xml files for `/.` and delete the found xml because we don't care about preserving FITS data for those hidden files.  If the script could either only run FITS on non-hidden files or delete them after running, before the folder gets zipped, that would be ideal.

**Done looks like**
The script accounts for hidden files and omits them before the FITS directory gets zipped.

**Comment by mccalluc** [comment]
FITS has no built-in options for ignoring particular files during scan, so removing them after generation seem like the only solution.

**Comment by Muraszko-wgbh** [comment]
@mccalluc Reopening. 
I found some fits xml for hidden files in a zipped folder I was working on.  I'll send the attachment in an email to you.

**Comment by mccalluc** [comment]
The zip didn't work. Could you run `tree` on the before and after? Maybe there's a weird character which confused the regex somehow?

**Comment by mccalluc** [comment]
@Muraszko : so I got it unzipped, but I haven't been able to reproduce. I was hoping there was something odd in the filenames, but I added to my fixture:

```
Public_Archives/Antiques_Roadshow/Antiques_Roadshow_To_Archives/Antiques_Season_20_Audio_Mix_Sessions_and_Web/S20_Web/2_Spokane/Saturday/S20_SpokaneStills/._IMG_1715.JPG
```

and at the end there is no FITS, as is appropriate.

**Comment by mccalluc** [comment]
@Muraszko : if you could update your gh-pages branch, try again, and let me know how it goes, that would be useful. If there are still problems, I'll need your help constructing a reproducer that I can run... If you target the immediate parent directory of the dot file, do you still have the same problem?

(I'm wondering if you're still on master, by chance? We could bring that back, and make it the default, but only push changes to the gh-pages branch as needed, if the current setup is confusing.)

**Comment by Muraszko-wgbh** [comment]
@mccalluc Thanks Chuck.
Nope, not confusing at the moment.  The hidden files and weird error when zipping problems seemed to be happening on files processed from the Avid edit share system.  I'll have more examples next week where we can test these changes.

**Comment by mccalluc** [comment]
If it does happen again, what would be really useful would be a small reproducer, and not just the output. Could the problem be re-created by targeting just a sub-sub-sub directory with invisible files? Also, if you want to take a look at the fixture and make sure the behavior around dot-directories is what you want, that might be a good thing.

**Comment by Muraszko-wgbh** [comment]
Working as it should for now.
